# Generated by Django 4.2.7 on 2023-12-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_categoria_noticia_categoria_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
