# Generated by Django 4.2.7 on 2023-12-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
