# Generated by Django 4.2.7 on 2023-12-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_noticia_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='cant_vistas',
            field=models.IntegerField(default=0),
        ),
    ]
