# Generated by Django 4.2.7 on 2023-12-12 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0006_comentarios_noticia_comentarios_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='comentarios_noticia',
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.AddField(
            model_name='noticia',
            name='comentarios',
            field=models.ManyToManyField(related_name='noticia_comentarios', to='noticias.comentario'),
        ),
    ]
