# Generated by Django 4.2.7 on 2023-12-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuseradmin_usuario_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagenes',
            field=models.ImageField(default='default.png', upload_to='user'),
        ),
    ]
