# Generated by Django 4.2.7 on 2023-12-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_genero_usuario_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagenes',
            field=models.ImageField(default='user/avatar.svg', upload_to='user'),
        ),
    ]
