# Generated by Django 4.2.7 on 2023-12-20 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acercade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacioncontacto',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='informacioncontacto',
            name='fecha_leido',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='informacioncontacto',
            name='user_leido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
