name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.6]
    
    services:
      mysql:
        image: mysql:8.0
        env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: blog_grupo9
        ports:
          - 3306:3306


    steps:
    - uses: actions/checkout@v3
    - name: Install Ubuntu dependencies
      run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libmysqlclient-dev libgirepository1.0-dev
      
    - name: Wait for MySQL to be ready
      run: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
            tar -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
            sudo mv dockerize /usr/local/bin/dockerize
            dockerize -wait tcp://localhost:3306 -timeout 2m
    - name: Set up database
      run: |
        mysql -h localhost -u root -p root -e "CREATE DATABASE IF NOT EXISTS blog_grupo9;"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}



    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      run: python manage.py migrate

    - name: Run Tests
      run: python manage.py test
